- name: Ping Matrix
  ansible.builtin.ping:

- name: Include Install
  include: install.yaml

- name: Include Firewalld
  include: firewalld.yaml
  when: groups['Caddy'] is defined and (groups['Caddy'] | length > 0)

- name: Include SELinux
  include: selinux.yaml
  when: (testing is not defined) or (testing is false)

- name: Include Postgres
  include: postgres.yaml

- name: Setup Matrix
  include: matrix_setup.yaml

- name: Add Caddy Config for Matrix
  delegate_to: "{{ groups['Caddy'][0] }}"
  ansible.builtin.template:
    src: ./templates/caddy_config.j2
    dest: /etc/caddy/sites-enabled/matrix_config
  notify:
    - Restart Caddy
  when: groups['Caddy'] is defined and (groups['Caddy'] | length > 0)
